# Generated by Django 4.2.1 on 2024-02-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('course_id', models.AutoField(primary_key=True, serialize=False)),
                ('course_description', models.TextField()),
                ('course_outcomes', models.TextField()),
                ('course_tags', models.CharField(max_length=100)),
                ('course_level', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('advanced', 'Advanced')], max_length=20)),
            ],
        ),
    ]
