# Generated by Django 4.2.1 on 2024-02-27 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_course_course_poster'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_title',
            field=models.TextField(default='title'),
        ),
    ]
