# Generated by Django 4.2.1 on 2024-02-27 11:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0005_alter_course_course_poster'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('vid_id', models.AutoField(primary_key=True, serialize=False)),
                ('vid_title', models.CharField(max_length=255)),
                ('vid_description', models.TextField()),
                ('vid_embedded_url', models.TextField()),
                ('likes', models.BooleanField(default=False)),
                ('playlist', models.BooleanField(default=False)),
                ('notes', models.TextField()),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('category', models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('app', 'App')], max_length=20)),
                ('video_tags', models.CharField(max_length=100)),
                ('vid_duration', models.CharField(max_length=20)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.course')),
            ],
        ),
    ]
