# Generated by Django 4.2.1 on 2024-02-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='category',
            field=models.CharField(choices=[('frontend', 'Frontend'), ('backend', 'Backend'), ('app', 'App'), ('gamedev', 'Game Development'), ('devops', 'Devops')], max_length=20),
        ),
    ]
