# Generated by Django 5.0.2 on 2024-02-28 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_watchlatervideo_likedvideo'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='course_author',
            field=models.TextField(default='author'),
        ),
    ]
